---

- name: Add php-fpm site conf
  template:
    backup: True
    src: php_fpm_www.conf.j2
    dest: "/etc/opt/remi/php72/php-fpm.d/{{ item.key }}.conf"
  with_dict: "{{ php_fpm_pools }}"
  notify: restart php-fpm